### ISSUE TITLE
Gateleen returns internal server error after erroneous put in logging

### ISSUE THREAD

**Issue by hiddenalpha** [swisspush/gateleen#206]
When putting some erroneous logging configuration to

> http://example.com/gateleen/server/admin/v1/logging

Gateleen will answer all further requests with an internal server error:

2017-10-25 16:55:53,824 isa-houston-int.ospa.pnet.ch int houston-23-2b4t5 ERROR RoutingContextImplBase - Unexpected exception in route
java.util.regex.PatternSyntaxException: Unclosed group near index 39
/houston/services/.*(?<!(all/position)$
                                       ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.accept(Unknown Source)
        at java.util.regex.Pattern.group0(Unknown Source)
        at java.util.regex.Pattern.sequence(Unknown Source)
        at java.util.regex.Pattern.expr(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)

Sample resource:

```
{
  "payload": {
    "filters": [
      {
        "url": "/houston/from/vehicles/[^/]+/audit/log"
      },
      {
        "url": "/houston/server/admin/v1/.*",
        "method": "PUT|DELETE"
      },
      {
        "url": "/houston/services/.*(?<!(all/position)$”,
        "method": "PUT|DELETE"
      },
      {
        "url": "/houston/from/.*"
      },
      {
        "url": "/houston/data/.*"
      },
      {
        "url": "/houston/server/.*"
      }
    ]
  }
}
```

This issue got moved from internal issue [ISAGD-4231]

**Comment by hiddenalpha** [comment]
**Closed:** Due to [merged PullRequest](https://github.com/swisspush/gateleen/pull/207).
