### ISSUE TITLE
Missing error handling when receiving eventBus messages

### ISSUE THREAD

**Issue by hiddenalpha** [swisspush/gateleen#247]
We observed a lot of NullPointerExceptions in one of our gateleen instances.

Seems to be a missing error handling in [gateleen-core/EventBusResourceStorage.java:L34](https://github.com/swisspush/gateleen/blob/v1.1.35/gateleen-core/src/main/java/org/swisspush/gateleen/core/storage/EventBusResourceStorage.java#L34). There we get a AsyncResult but we miss to check AsyncResult#succeeded() before calling AsyncResult#result(). Instead we directly use value without any check:

```
message.result().body()
```

Log:

```
...
ERROR ContextImpl - Unhandled exception
java.lang.NullPointerException
        at org.swisspush.gateleen.core.storage.EventBusResourceStorage$1.handle(EventBusResourceStorage.java:34)
        at org.swisspush.gateleen.core.storage.EventBusResourceStorage$1.handle(EventBusResourceStorage.java:31)
        at io.vertx.core.eventbus.impl.HandlerRegistration.sendAsyncResultFailure(HandlerRegistration.java:127)
        at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$new$0(HandlerRegistration.java:78)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by hiddenalpha** [comment]
As discussed, I'll apply same strategy as in redisques shortly:
Don't change exposed behavior. Simply properly log whats going on.
