### ISSUE TITLE
Error: Request has already been read

### ISSUE THREAD

**Issue by mcweba** [swisspush/gateleen#293]
The _HandlerRegistration_ class sometimes logs errors about failing to handle messages. The Result is always a _IllegalStateException_ like the example below:

```
java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:586)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handler(HttpServerRequestImpl.java:306)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:44)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:44)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:16)
	at io.vertx.core.streams.impl.PumpImpl.start(PumpImpl.java:82)
	at io.vertx.core.streams.impl.PumpImpl.start(PumpImpl.java:37)
	at org.swisspush.gateleen.routing.Forwarder.handleRequest(Forwarder.java:290)
	at org.swisspush.gateleen.routing.Forwarder.lambda$handle$0(Forwarder.java:137)
	at org.swisspush.gateleen.core.storage.EventBusResourceStorage$1.handle(EventBusResourceStorage.java:46)
	at org.swisspush.gateleen.core.storage.EventBusResourceStorage$1.handle(EventBusResourceStorage.java:34)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$convertHandler$3(EventBusImpl.java:348)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:261)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:239)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:565)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:524)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
It seems that these errors only occur for requests handled by a routing rule with a _profile_ property. See _Forwarder.class_ line 137 and 140.

**Additional Hints to verify**
* Add a req.pause() just before line 140 to also pause the request for "non-profile"-cases
* in _Forwarder.class_ lines 275-290: Only call _pump.start()_ when _!req.isEnded()_
* Do incoming GET requests have a content-length header value?

**Comment by mcweba** [comment]
Fixed in version [v1.1.50](https://github.com/swisspush/gateleen/releases/tag/v1.1.50)
