### ISSUE TITLE
Reduce DeltaHandler logs for not found collections

### ISSUE THREAD

**Issue by mcweba** [swisspush/gateleen#373]
When making delta requests to a collection which does not exist, the following error is logged correctly:

```
2021-06-08 08:51:46,612 vnecri2 int  crush ERROR DeltaHandler - YL8Tgt7UPkSYyLF72OnNegAALQU Failed to handle get for collection
```
However, also the stacktrace of the corresponding _ResourceCollectionException_ is logged.

Example:
```
org.swisspush.gateleen.core.util.ResourceCollectionException: Not Found
	at org.swisspush.gateleen.core.util.ExpansionDeltaUtil.checkResponse(ExpansionDeltaUtil.java:254)
	at org.swisspush.gateleen.core.util.ExpansionDeltaUtil.verifyCollectionResponse(ExpansionDeltaUtil.java:219)
	at org.swisspush.gateleen.delta.DeltaHandler.lambda$null$10(DeltaHandler.java:252)
	at org.swisspush.gateleen.core.http.LocalHttpServerResponse$1.lambda$bodyHandler$0(LocalHttpServerResponse.java:69)
	at org.swisspush.gateleen.core.http.BufferBridge.doEnd(BufferBridge.java:75)
	at org.swisspush.gateleen.core.http.LocalHttpServerResponse.end(LocalHttpServerResponse.java:269)
	at org.swisspush.gateleen.routing.StorageForwarder.lambda$null$1(StorageForwarder.java:141)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$convertHandler$3(EventBusImpl.java:348)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:261)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:239)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:565)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:524)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
This results in lots of unnecessary log statements.

**Solution**
Do not log exception when the response status code is _404 Not Found_. Also change the type of the log from _ERROR_ to _INFO_ in this case.

**Comment by mcweba** [comment]
Fixed in version [v1.1.70](https://github.com/swisspush/gateleen/releases/tag/v1.1.70)
